### ISSUE TITLE
Multiple FB Logins

### ISSUE THREAD

**Issue by samiajia** [Peksa/pek.so#2]
Hi Peksa, will it be possible to enable multiple FB logins to this app?

Thank you.

**Comment by Peksa** [comment]
Sorry for the late reply!

I just tried it out, and yes it is possible to add multiple people as administrators! :)

You need to add their app specific user IDs to your IAM Trust Relationship policy. Simply change the string to an array of strings:

``` json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Federated": "graph.facebook.com"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "graph.facebook.com:app_id": "602729056487961",
          "graph.facebook.com:id": ["717273996", "second-id", "etc.."]
        }
      }
    }
  ]
}
```

Not quite sure what the best way is to find out their app specific user id's though..
