### ISSUE TITLE
Error on initial page load when no redirects in S3 bucket

### ISSUE THREAD

**Issue by crcastle** [Peksa/pek.so#5]
If there are zero redirects in the S3 bucket on app load I get an error -- i.e. the initial user experience is an error.  It looks like this is because the callback is never called in [this block](https://github.com/Peksa/pek.so/blob/master/js/app.js#L126-L129).

Working on a fix right now...

**Comment by Peksa** [comment]
Thanks! I merged the PR! https://github.com/Peksa/pek.so/commit/0d7a16c0d3ccbfcdb93e2ecd319834dbc16db5eb
